import {
  ANNUAL,
  APR,
  AUG,
  BENEFICIAL_INSECTS,
  BIENNIAL,
  BUMBLE_BEE,
  DEER_RESISTANT,
  DRY,
  FORB,
  FULL_SHADE,
  FULL_SUN,
  GRASS,
  JUL,
  JUN,
  LARVAL_HOST,
  MAR,
  MAY,
  MOIST,
  NEST_MATERIALS,
  NEST_SITE,
  NEST_THATCH,
  NOV,
  OCT,
  PARTIAL_SUN,
  PERENNIAL,
  SEDGE,
  SEP,
  SHRUB,
  SPECIALIST_BEE,
  TREE,
  WET,
} from "./constants";
import { Plant } from "./types";

export const greatLakesPlantList: Plant[] = [
  {
    scientificName: "Agastache scrophulariifolia",
    commonName: "Purple giant hyssop",
    bloom: [JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [DRY, MOIST],
    additionalDetails: [BENEFICIAL_INSECTS, BUMBLE_BEE],
  },
  {
    scientificName: "Amelanchier laevis",
    commonName: "Allegheny serviceberry",
    bloom: [MAR, APR, MAY],
    life: [PERENNIAL],
    form: [TREE, SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [DRY, MOIST],
    additionalDetails: [LARVAL_HOST, BENEFICIAL_INSECTS],
  },
  {
    scientificName: "Asclepias incarnata",
    commonName: "Swamp milkweed",
    bloom: [JUN, JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Asclepias syriaca",
    commonName: "Common milkweed",
    bloom: [JUN, JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Asclepias tuberosa",
    commonName: "Butterfly milkweed",
    bloom: [JUN, JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Carex bebbii",
    commonName: "Bebb's sedge",
    bloom: [MAY, JUN],
    life: [PERENNIAL],
    form: [SEDGE],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [WET],
  },
  {
    scientificName: "Carex cristatella",
    commonName: "Crested sedge",
    bloom: [MAY, JUN],
    life: [PERENNIAL],
    form: [SEDGE],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [MOIST, WET],
    additionalDetails: [LARVAL_HOST],
  },
  {
    scientificName: "Carex scoparia",
    commonName: "Broom sedge",
    bloom: [MAY, JUN],
    life: [PERENNIAL],
    form: [SEDGE],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [MOIST, WET],
  },
  {
    scientificName: "Carex vulpinoidea",
    commonName: "Fox sedge",
    bloom: [APR, MAY],
    life: [PERENNIAL],
    form: [SEDGE],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [DEER_RESISTANT],
  },
  {
    scientificName: "Ceanothus americanus",
    commonName: "New Jersey tea",
    bloom: [JUN, JUL],
    life: [PERENNIAL],
    form: [SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
    ],
  },
  {
    scientificName: "Cirsium discolor",
    commonName: "Field thistle",
    bloom: [AUG, SEP, OCT],
    life: [BIENNIAL, PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      NEST_MATERIALS,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Coreopsis lanceolata",
    commonName: "Lanceleaf tickseed",
    bloom: [APR, MAY, JUN],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Crataegus spp.",
    commonName: "Hawthorn",
    bloom: [APR, MAY],
    life: [PERENNIAL],
    form: [TREE, SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Dalea purpurea",
    commonName: "Purple prairie clover",
    bloom: [JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Desmodium canadense",
    commonName: "Showy tick-trefoil",
    bloom: [JUN, JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_MATERIALS,
    ],
  },
  {
    scientificName: "Elymus canadensis",
    commonName: "Canada wild rye",
    bloom: [JUL, AUG],
    life: [PERENNIAL],
    form: [GRASS],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [LARVAL_HOST, NEST_THATCH, DEER_RESISTANT],
  },
  {
    scientificName: "Eupatorium perfoliatum",
    commonName: "Common boneset",
    bloom: [JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Euthamia graminifolia",
    commonName: "Grass-leaved goldenrod",
    bloom: [JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
    ],
  },
  {
    scientificName: "Eutrochium maculatum",
    commonName: "Spotted Joe Pye weed",
    bloom: [JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [WET],
    additionalDetails: [LARVAL_HOST, BENEFICIAL_INSECTS, BUMBLE_BEE, NEST_SITE],
  },
  {
    scientificName: "Gentiana andrewsii",
    commonName: "Closed bottle gentian",
    bloom: [AUG, SEP, OCT],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [MOIST],
    additionalDetails: [BENEFICIAL_INSECTS, BUMBLE_BEE, DEER_RESISTANT],
  },
  {
    scientificName: "Geranium maculatum",
    commonName: "Spotted geranium",
    bloom: [APR, MAY],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
    ],
  },
  {
    scientificName: "Helenium autumnale",
    commonName: "Common sneezeweed",
    bloom: [SEP, OCT, NOV],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Helianthus spp.",
    commonName: "Sunflower",
    bloom: [JUN, JUL, AUG, SEP],
    life: [ANNUAL, PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Heliopsis helianthoides",
    commonName: "Smooth oxeye",
    bloom: [JUN, JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Koeleria macrantha",
    commonName: "Prairie Junegrass",
    bloom: [MAY, JUN, JUL],
    life: [PERENNIAL],
    form: [GRASS],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY],
    additionalDetails: [LARVAL_HOST, NEST_THATCH, DEER_RESISTANT],
  },
  {
    scientificName: "Liatris spp.",
    commonName: "Blazing star",
    bloom: [JUL, AUG, SEP, OCT],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
    ],
  },
  {
    scientificName: "Lobelia siphilitica",
    commonName: "Great blue lobelia",
    bloom: [JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Lupinus perennis",
    commonName: "Wild lupine",
    bloom: [APR, MAY, JUN],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [DRY],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
    ],
  },
  {
    scientificName: "Monarda fistulosa",
    commonName: "Wild bergamot",
    bloom: [JUN, JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Panicum virgatum",
    commonName: "Switchgrass",
    bloom: [JUL, AUG],
    life: [PERENNIAL],
    form: [GRASS],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST, WET],
    additionalDetails: [LARVAL_HOST, NEST_THATCH, DEER_RESISTANT],
  },
  {
    scientificName: "Penstemon gracilis",
    commonName: "Slender beardtongue",
    bloom: [MAY, JUN],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [SPECIALIST_BEE],
  },
  {
    scientificName: "Penstemon hirsutus",
    commonName: "Hairy beardtongue",
    bloom: [JUN, JUL],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
    ],
  },
  {
    scientificName: "Physocarpus opulifolius",
    commonName: "Common ninebark",
    bloom: [APR, MAY, JUN],
    life: [PERENNIAL],
    form: [SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST],
    additionalDetails: [LARVAL_HOST, BENEFICIAL_INSECTS, BUMBLE_BEE],
  },
  {
    scientificName: "Prunus virginiana",
    commonName: "Black chokecherry",
    bloom: [APR, MAY],
    life: [PERENNIAL],
    form: [TREE, SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Pycnanthemum virginianum",
    commonName: "Virginia mountain mint",
    bloom: [JUN, JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Ratibida pinnata",
    commonName: "Pinnate prairie coneflower",
    bloom: [JUN, JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Rosa blanda",
    commonName: "Smooth wild rose",
    bloom: [MAY, JUN],
    life: [PERENNIAL],
    form: [SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      NEST_MATERIALS,
    ],
  },
  {
    scientificName: "Salix humilis",
    commonName: "Prairie willow",
    bloom: [MAR, APR, MAY],
    life: [PERENNIAL],
    form: [SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Schizachyrium scoparium",
    commonName: "Little bluestem",
    bloom: [AUG, SEP],
    life: [PERENNIAL],
    form: [GRASS],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [LARVAL_HOST, NEST_THATCH, DEER_RESISTANT],
  },
  {
    scientificName: "Solidago speciosa",
    commonName: "Showy goldenrod",
    bloom: [AUG, SEP],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Sorghastrum nutans",
    commonName: "Indiangrass",
    bloom: [JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [GRASS],
    sun: [FULL_SUN],
    soil: [DRY, MOIST, WET],
    additionalDetails: [LARVAL_HOST, NEST_THATCH, DEER_RESISTANT],
  },
  {
    scientificName: "Spiraea alba",
    commonName: "White meadowsweet",
    bloom: [JUL, AUG, SEP],
    life: [PERENNIAL],
    form: [SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_MATERIALS,
    ],
  },
  {
    scientificName: "Symphyotrichum lateriflorum",
    commonName: "Calico aster",
    bloom: [AUG, SEP, OCT],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
    ],
  },
  {
    scientificName: "Symphyotrichum novae-angliae",
    commonName: "New England aster",
    bloom: [AUG, SEP, OCT],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
    ],
  },
  {
    scientificName: "Tilia americana",
    commonName: "American basswood",
    bloom: [MAY, JUN],
    life: [PERENNIAL],
    form: [TREE],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [LARVAL_HOST, BENEFICIAL_INSECTS, BUMBLE_BEE],
  },
  {
    scientificName: "Tradescantia ohiensis",
    commonName: "Ohio spiderwort",
    bloom: [APR, MAY, JUN],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST, WET],
    additionalDetails: [BENEFICIAL_INSECTS, BUMBLE_BEE],
  },
  {
    scientificName: "Verbena stricta",
    commonName: "Hoary verbena",
    bloom: [JUN, JUL, AUG, SEP],
    life: [ANNUAL, PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN],
    soil: [DRY, MOIST],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
    ],
  },
  {
    scientificName: "Veronicastrum virginicum",
    commonName: "Culver's root",
    bloom: [JUN, JUL, AUG],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
  {
    scientificName: "Viburnum spp.",
    commonName: "Viburnum",
    bloom: [MAY, JUN, JUL],
    life: [PERENNIAL],
    form: [TREE, SHRUB],
    sun: [FULL_SUN, PARTIAL_SUN, FULL_SHADE],
    soil: [DRY, MOIST, WET],
    additionalDetails: [LARVAL_HOST, BENEFICIAL_INSECTS, BUMBLE_BEE, NEST_SITE],
  },
  {
    scientificName: "Zizia aurea",
    commonName: "Golden Alexanders",
    bloom: [APR, MAY, JUN],
    life: [PERENNIAL],
    form: [FORB],
    sun: [FULL_SUN, PARTIAL_SUN],
    soil: [DRY, MOIST, WET],
    additionalDetails: [
      LARVAL_HOST,
      SPECIALIST_BEE,
      BENEFICIAL_INSECTS,
      BUMBLE_BEE,
      NEST_SITE,
      DEER_RESISTANT,
    ],
  },
];
