type Plant = {
  commonName: string;
};

export const plantList: Record<string, Plant> = {
  agastacheScrophulariifolia: { commonName: "Purple giant hyssop" },
  amelanchierLaevis: { commonName: "Allegheny serviceberry" },
  asclepiasIncarnata: { commonName: "Swamp milkweed" },
  asclepiasSyriaca: { commonName: "Common milkweed" },
  asclepiasTuberosa: { commonName: "Butterfly milkweed" },
  carexBebbii: { commonName: "Bebb's sedge" },
  carexCristatella: { commonName: "Crested sedge" },
  carexScoparia: { commonName: "Broom sedge" },
  carexVulpinoidea: { commonName: "Fox sedge" },
  ceanothusAmericanus: { commonName: "New Jersey tea" },
  cirsiumDiscolor: { commonName: "Field thistle" },
  coreopsisLanceolata: { commonName: "Lanceleaf tickseed" },
  crataegusSpp: { commonName: "Hawthorn" },
  daleaPurpurea: { commonName: "Purple prairie clover" },
  desmodiumCanadense: { commonName: "Showy tick-trefoil" },
  elymusCanadensis: { commonName: "Canada wild rye" },
  eupatoriumPerfoliatum: { commonName: "Common boneset" },
  euthamiaGraminifolia: { commonName: "Grass-leaved goldenrod" },
  eutrochiumMaculatum: { commonName: "Spotted Joe Pye weed" },
  gentianaAndrewsii: { commonName: "Closed bottle gentian" },
  geraniumMaculatum: { commonName: "Spotted geranium" },
  heleniumAutumnale: { commonName: "Common sneezeweed" },
  helianthusSpp: { commonName: "Sunflower" },
  heliopsisHelianthoides: { commonName: "Smooth oxeye" },
  koeleriaMacrantha: { commonName: "Prairie Junegrass" },
  liatrisSpp: { commonName: "Blazing star" },
  lobeliaSiphilitica: { commonName: "Great blue lobelia" },
  lupinusPerennis: { commonName: "Wild lupine" },
  monardaFistulosa: { commonName: "Wild bergamot" },
  panicumVirgatum: { commonName: "Switchgrass" },
  penstemonGracilis: { commonName: "Slender beardtongue" },
  penstemonHirsutus: { commonName: "Hairy beardtongue" },
  physocarpusOpulifolius: { commonName: "Common ninebark" },
  prunusVirginiana: { commonName: "Black chokecherry" },
  pycnanthemumVirginianum: { commonName: "Virginia mountain mint" },
  ratibidaPinnata: { commonName: "Pinnate prairie coneflower" },
  rosaBlanda: { commonName: "Smooth wild rose" },
  salixHumilis: { commonName: "Prairie willow" },
  schizachyriumScoparium: { commonName: "Little bluestem" },
  solidagoSpeciosa: { commonName: "Showy goldenrod" },
  sorghastrumNutans: { commonName: "Indiangrass" },
  spiraeaAlba: { commonName: "White meadowsweet" },
  symphyotrichumLateriflorum: { commonName: "Calico aster" },
  symphyotrichumNovaeAngliae: { commonName: "New England aster" },
  tiliaAmericana: { commonName: "American basswood" },
  tradescantiaOhiensis: { commonName: "Ohio spiderwort" },
  verbenaStricta: { commonName: "Hoary verbena" },
  veronicastrumVirginicum: { commonName: "Culver's root" },
  viburnumSpp: { commonName: "Viburnum" },
  ziziaAurea: { commonName: "Golden Alexanders" },
};
