name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: TypeScript Check
        run: npx tsc --noEmit
      - name: ESLint
        run: npx eslint . --ext .ts,.tsx
      - name: Run Tests
        run: npm run jest
      # - name: Expo Prebuild Check
      #   run: npx expo prebuild --no-install
